#!/bin/sh

user="jonasprobst"
repo="wandering-pillar-cli"

rm -rf myprojectname
curl -l -k https://codeload.github.com/$user/$repo/zip/master > archive.zip
unzip archive.zip -d .
mv $repo-master $repo
rm -f archive.zip
